name: "Mergify Dependencies Conflicts Resolver"
author: "Mergifyio"

description: "Resolve conflicts in dependencies version files."

inputs:
  base:
    description: "Your base branch"
    required: true
    default: "main"
  github_token:
    description: "Personal Access Token"
    required: true
  user:
    description: "User associated to the token"
    required: true
  email:
    description: "Email associated to the token"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
        token: ${{ inputs.github_token }}

    - name: Fetch required python version from pyproject.toml
      id: python-version
      run: |
        version=$(cat pyproject.toml | grep -w "python =" | sed -n 's/.*[^0-9.]\([0-9]\+\(\.[0-9]\+\)*\).*/\1/p;q')
        echo "version=$version" >> $GITHUB_OUTPUT
      shell: bash

    - name: Setup Python
      uses: actions/setup-python@v4.1.0
      with:
        python-version: ${{ steps.python-version.outputs.version }}

    - name: Resolve conflicts and push
      run: ${{ github.action_path }}/resolver.sh ${{ inputs.base }}
      shell: bash
      env:
        BASE_BRANCH: ${{ inputs.base }}
        USER: ${{ inputs.user }}
        EMAIL: ${{ inputs.email }}
#        GH_TOKEN: ${{ inputs.token }}
