name: "Mergify Dependencies Conflicts Resolver"
author: "Mergifyio"

description: "Resolve conflicts in dependencies version files."

inputs:
  head-repo:
    description: "The full name of the head repository"
    required: true
  head:
    description: "The head branch"
    required: true
  base:
    description: "Your base branch"
    required: true
    default: "main"
  user:
    description: "User associated to the token used to checkout or to the GITHUB_TOKEN (defaults to github action user)"
    required: true
    default: "github-actions"
  email:
    description: "Email associated to the token used to checkout or to the GITHUB_TOKEN (defaults to github action email)"
    required: true
    default: "github-actions@github.com"

runs:
  using: composite
  steps:
    - name: Fetch required python version from pyproject.toml
      id: python-version
      run: |
        version=$(cat pyproject.toml | grep -w "python =" | sed -n 's/.*[^0-9.]\([0-9]\+\(\.[0-9]\+\)*\).*/\1/p;q')
        echo "version=$version" >> $GITHUB_OUTPUT
      shell: bash

    - name: Setup Python
      uses: actions/setup-python@v4.1.0
      with:
        python-version: ${{ steps.python-version.outputs.version }}

#    - name: Resolve conflicts and push
#      run: ${{ github.action_path }}/resolver.sh ${{ inputs.base }}
#      shell: bash
#      env:
#        REPO: ${{ inputs.head-repo }}
#        HEAD_BRANCH: ${{ inputs.head }}
#        BASE_BRANCH: ${{ inputs.base }}
#        USER: ${{ inputs.user }}
#        EMAIL: ${{ inputs.email }}

    - name: Resolve conflicts and push (new)
      run: ${{ github.action_path }}/resolver.sh ${{ inputs.base }}
      shell: bash
      env:
        HEAD_REPO: ${{ inputs.head-repo }}
        HEAD_BRANCH: ${{ inputs.head }}
        BASE_BRANCH: ${{ inputs.base }}
        USER: ${{ inputs.user }}
        EMAIL: ${{ inputs.email }}
