name: "Mergify Dependencies Conflicts Resolver"
author: "Mergifyio"

description: "Resolve conflicts in dependencies version files."

inputs:
  base:
    description: "Your base branch"
    required: true
    default: "main"

runs:
  using: composite
  steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Resolve conflicts and push
      run: ${{ github.action_path }}/resolver.sh ${{ inputs.base }}
      shell: bash
