name: "Mergify Dependencies Conflicts Resolver"
author: "Mergifyio"

description: "Resolve conflicts in dependencies version files."

inputs:
  base:
    description: "Your base branch"
    required: true
    default: "main"
  token:
    description: 'The GitHub token to use for API requests'
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

#    - name: Setup Python
#      uses: actions/setup-python@v4.1.0
#      with:
#        python-version: 3.11.4

    - name: Resolve conflicts and push
      run: ${{ github.action_path }}/resolver.sh ${{ inputs.base }}
      shell: bash
      env:
        BASE: ${{ inputs.base }}
        GH_TOKEN: ${{ inputs.token }}
